"""Universal Agent Hooks — Auto-connect, auto-session, auto-brief for all agents.

Unlike the Claude Code-only SessionStart hook, this system works with ANY MCP
client by generating agent-specific configuration files that auto-connect to
LEVH when the agent starts.

Supported agents:
  - Claude Code:     .claude/settings.json SessionStart hook
  - Claude Desktop:  claude_desktop_config.json (injected tool)
  - Cursor:          .cursor/mcp.json + .cursorrules
  - VS Code/Cline:   .vscode/mcp.json + settings
  - Windsurf:        .windsurf/mcp.json
  - Generic MCP:     any client that reads mcpServers config

Each agent gets:
  1. Auto-connection to LEVH MCP server
  2. Auto-session creation on first tool use
  3. Continuity brief injection at session start
  4. Periodic checkpoint capability
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any


# ── Agent hook configurations ────────────────────────────────────────

class AgentHookConfig:
    """Configuration for a specific agent's auto-connect hook."""

    def __init__(
        self,
        name: str,
        display_name: str,
        config_path: str,
        config_format: str = "json",
        supports_session_start: bool = False,
        supports_mcp: bool = True,
    ):
        self.name = name
        self.display_name = display_name
        self.config_path = config_path
        self.config_format = config_format
        self.supports_session_start = supports_session_start
        self.supports_mcp = supports_mcp


SUPPORTED_AGENTS: dict[str, AgentHookConfig] = {
    "claude-code": AgentHookConfig(
        name="claude-code",
        display_name="Claude Code",
        config_path=".claude/settings.json",
        supports_session_start=True,
        supports_mcp=True,
    ),
    "claude-desktop": AgentHookConfig(
        name="claude-desktop",
        display_name="Claude Desktop",
        config_path="claude_desktop_config.json",
        supports_session_start=False,
        supports_mcp=True,
    ),
    "cursor": AgentHookConfig(
        name="cursor",
        display_name="Cursor",
        config_path=".cursor/mcp.json",
        supports_session_start=False,
        supports_mcp=True,
    ),
    "vscode": AgentHookConfig(
        name="vscode",
        display_name="VS Code (Cline)",
        config_path=".vscode/mcp.json",
        supports_session_start=False,
        supports_mcp=True,
    ),
    "windsurf": AgentHookConfig(
        name="windsurf",
        display_name="Windsurf",
        config_path=".windsurf/mcp.json",
        supports_session_start=False,
        supports_mcp=True,
    ),
}


# ── Hook content templates ──────────────────────────────────────────

# The auto-connect script that runs when an agent starts.
# It creates a session, loads the brief, and prints it.
_AUTO_CONNECT_TEMPLATE = '''#!/bin/sh
{marker}
# LEVH Universal Auto-Connect Hook
# Automatically connects to LEVH, creates a session, and loads the brief.
# Works for any MCP client — installed by `levh hook install --client {client}`.

LEVH_URL="${{LEVH_URL:-http://localhost:8000}}"
SQLITE_DB_PATH="${{SQLITE_DB_PATH:-{db_path}}}"
export SQLITE_DB_PATH

# 1. Create a session for this agent
SESSION_RESPONSE=$("{python}" -P -c "
import urllib.request, json, sys
try:
    req = urllib.request.Request(
        f'{levh_url}/api/sessions',
        data=json.dumps({{'name': '{agent_display} Session', 'metadata': json.dumps({{'agent': '{client}', 'auto': True}})}}).encode(),
        headers={{'Content-Type': 'application/json'}},
        method='POST'
    )
    resp = urllib.request.urlopen(req, timeout=5)
    data = json.loads(resp.read())
    print(data.get('id', ''))
except Exception:
    pass
" 2>/dev/null) || true

# 2. Get the continuity brief
BRIEF=$("{python}" -P -m server.cli continue --limit {limit} --if-any 2>/dev/null) || exit 0

# 3. Print the brief (agent will see it)
[ -n "$BRIEF" ] || exit 0
printf '%s\\n' "$BRIEF"
exit 0
'''

# MCP config injection for agents that support it
_MCP_CONFIG_INJECTION = '''
# LEVH Auto-Connect: This config auto-connects to your local LEVH memory.
# Generated by `levh hook install --client {client}`
# The MCP server provides 62 tools for memory management.
'''

# Checkpoint template — runs periodically to save state
_CHECKPOINT_TEMPLATE = '''#!/bin/sh
{marker}
# LEVH Checkpoint — saves current work state periodically.
# Installed by `levh hook install --client {client} --with-checkpoint`

SQLITE_DB_PATH="${{SQLITE_DB_PATH:-{db_path}}}"
export SQLITE_DB_PATH

# Create a checkpoint with the recent activity
"{python}" -P -m server.cli checkpoint \\
    --agent "{client}" \\
    --title "Auto checkpoint" \\
    --type auto \\
    2>/dev/null || true

exit 0
'''


def _resolved_db_path() -> str:
    """Absolute path to the database."""
    return os.path.abspath(os.getenv("SQLITE_DB_PATH", "./stackmemory.db"))


def _levh_url() -> str:
    """LEVH server URL."""
    return os.getenv("LEVH_URL", "http://localhost:8000")


# ── Installers ───────────────────────────────────────────────────────

def install_claude_code_hook(limit: int = 5, with_checkpoint: bool = False) -> dict:
    """Install the SessionStart hook for Claude Code."""
    from .hooks import _install_session_hook
    result = _install_session_hook(limit)
    return {"ok": result == 0, "agent": "claude-code"}


def install_cursor_hook(limit: int = 5) -> dict:
    """Install auto-connect for Cursor IDE."""
    config_path = Path(".cursor/mcp.json")
    config_path.parent.mkdir(parents=True, exist_ok=True)

    entry = {
        "command": "levh",
        "args": ["mcp", "stdio"],
        "cwd": os.getcwd(),
        "env": {
            "LEVH_MCP_PROFILE": "work",
            "SQLITE_DB_PATH": _resolved_db_path(),
        },
    }

    if config_path.exists():
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            config = {}
    else:
        config = {}

    servers = config.setdefault("mcpServers", {})
    servers["levh"] = entry
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    # Also create .cursorrules with continuity brief
    rules_path = Path(".cursorrules")
    _write_cursorrules(rules_path)

    return {"ok": True, "agent": "cursor", "config_path": str(config_path)}


def install_vscode_hook(limit: int = 5) -> dict:
    """Install auto-connect for VS Code (Cline extension)."""
    config_path = Path(".vscode/mcp.json")
    config_path.parent.mkdir(parents=True, exist_ok=True)

    entry = {
        "command": "levh",
        "args": ["mcp", "stdio"],
        "cwd": os.getcwd(),
        "env": {
            "LEVH_MCP_PROFILE": "work",
            "SQLITE_DB_PATH": _resolved_db_path(),
        },
    }

    if config_path.exists():
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            config = {}
    else:
        config = {}

    servers = config.setdefault("mcpServers", {})
    servers["levh"] = entry
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    return {"ok": True, "agent": "vscode", "config_path": str(config_path)}


def install_windsurf_hook(limit: int = 5) -> dict:
    """Install auto-connect for Windsurf."""
    config_path = Path(".windsurf/mcp.json")
    config_path.parent.mkdir(parents=True, exist_ok=True)

    entry = {
        "command": "levh",
        "args": ["mcp", "stdio"],
        "cwd": os.getcwd(),
        "env": {
            "LEVH_MCP_PROFILE": "work",
            "SQLITE_DB_PATH": _resolved_db_path(),
        },
    }

    if config_path.exists():
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            config = {}
    else:
        config = {}

    servers = config.setdefault("mcpServers", {})
    servers["levh"] = entry
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    return {"ok": True, "agent": "windsurf", "config_path": str(config_path)}


def install_claude_desktop_hook(limit: int = 5) -> dict:
    """Install auto-connect for Claude Desktop."""
    # Claude Desktop config is in OS-specific location
    # We generate it in the project root for the user to copy
    config_path = Path("claude_desktop_config_levh.json")

    entry = {
        "command": "levh",
        "args": ["mcp", "stdio"],
        "cwd": os.getcwd(),
        "env": {
            "LEVH_MCP_PROFILE": "work",
            "SQLITE_DB_PATH": _resolved_db_path(),
        },
    }

    config = {"mcpServers": {"levh": entry}}
    config_path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    return {
        "ok": True,
        "agent": "claude-desktop",
        "config_path": str(config_path),
        "note": "Copy this config to your Claude Desktop settings",
    }


def _write_cursorrules(path: Path) -> None:
    """Write .cursorrules with LEVH continuity brief instructions."""
    content = """# LEVH Memory Integration

When starting a new session in this project, run this command to load your memory:
```
levh continue --limit 5 --if-any
```

This will show you:
- Rules learned from mistakes (never repeat these)
- Pinned memories (always remember)
- Recent sessions and what was worked on
- Active files and recent changes
- Decisions made
- Blockers and TODOs

You can also:
- Store memories: `levh capture "what to remember"`
- Ask your memory: Use the `ask_memory` MCP tool
- Recall memories: Use the `recall_memory` MCP tool
"""
    path.write_text(content, encoding="utf-8")


# ── Unified install ──────────────────────────────────────────────────

def install_universal_hook(
    client: str = "all",
    limit: int = 5,
    with_checkpoint: bool = False,
) -> dict:
    """Install hooks for one or all supported agents.

    Args:
        client: Agent name or "all" for every supported agent.
        limit: Number of sessions to include in the continuity brief.
        with_checkpoint: Also install checkpoint hook (where supported).

    Returns:
        Dict mapping agent name to installation result.
    """
    results = {}

    if client == "all":
        agents = list(SUPPORTED_AGENTS.keys())
    else:
        agents = [client] if client in SUPPORTED_AGENTS else [client]

    for agent in agents:
        try:
            if agent == "claude-code":
                results[agent] = install_claude_code_hook(limit, with_checkpoint)
            elif agent == "cursor":
                results[agent] = install_cursor_hook(limit)
            elif agent == "vscode":
                results[agent] = install_vscode_hook(limit)
            elif agent == "windsurf":
                results[agent] = install_windsurf_hook(limit)
            elif agent == "claude-desktop":
                results[agent] = install_claude_desktop_hook(limit)
            else:
                results[agent] = {"ok": False, "error": f"Unknown agent: {agent}"}
        except Exception as exc:
            results[agent] = {"ok": False, "error": str(exc)}

    return results


def uninstall_universal_hook(client: str = "all") -> dict:
    """Uninstall hooks for one or all agents."""
    results = {}

    if client == "all":
        agents = list(SUPPORTED_AGENTS.keys())
    else:
        agents = [client] if client in SUPPORTED_AGENTS else [client]

    for agent in agents:
        try:
            if agent == "claude-code":
                from .hooks import _uninstall_session_hook
                result = _uninstall_session_hook()
                results[agent] = {"ok": result == 0}
            elif agent == "cursor":
                config_path = Path(".cursor/mcp.json")
                if config_path.exists():
                    config = json.loads(config_path.read_text(encoding="utf-8"))
                    config.get("mcpServers", {}).pop("levh", None)
                    config_path.write_text(json.dumps(config, indent=2) + "\n")
                results[agent] = {"ok": True}
            elif agent == "vscode":
                config_path = Path(".vscode/mcp.json")
                if config_path.exists():
                    config = json.loads(config_path.read_text(encoding="utf-8"))
                    config.get("mcpServers", {}).pop("levh", None)
                    config_path.write_text(json.dumps(config, indent=2) + "\n")
                results[agent] = {"ok": True}
            elif agent == "windsurf":
                config_path = Path(".windsurf/mcp.json")
                if config_path.exists():
                    config = json.loads(config_path.read_text(encoding="utf-8"))
                    config.get("mcpServers", {}).pop("levh", None)
                    config_path.write_text(json.dumps(config, indent=2) + "\n")
                results[agent] = {"ok": True}
            else:
                results[agent] = {"ok": False, "error": f"Unknown agent: {agent}"}
        except Exception as exc:
            results[agent] = {"ok": False, "error": str(exc)}

    return results
