"""Scaffolding for a new MCP server that uses LEVH as its memory.

`levh mcp init <name>` writes a small, working FastMCP server plus the files
needed to run it. The generated project does not vendor LEVH — it imports the
installed package and talks to the same SQLite database the rest of LEVH uses,
so a memory stored by the generated server is visible in the dashboard and to
every other MCP client.

Everything here is pure string building and file writing: no network, no
templates engine, no new dependency.
"""

from __future__ import annotations

import re
from pathlib import Path

TEMPLATES = ("python",)
DEFAULT_TEMPLATE = "python"


class ScaffoldError(RuntimeError):
    """Raised when a project cannot be generated."""


def normalize_name(name: str) -> str:
    """Validate a project name and return it unchanged.

    Kept strict rather than sanitizing: the name becomes a directory, a Python
    module, and a server identity, and silently rewriting it would surprise
    whoever typed it.
    """
    cleaned = (name or "").strip()
    if not cleaned:
        raise ScaffoldError("project name is required")
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9._-]*", cleaned):
        raise ScaffoldError(
            f"invalid project name '{name}'. Use letters, digits, dot, dash or "
            "underscore, starting with a letter."
        )
    return cleaned


def module_name(name: str) -> str:
    """The importable module name for a project name."""
    return re.sub(r"[.-]", "_", name).lower()


def _server_py(name: str, with_memory: bool, profile: str) -> str:
    if not with_memory:
        return f'''"""{name} — an MCP server.

Generated by `levh mcp init`. Add your own tools below.
"""

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("{name}")


@mcp.tool()
def hello(who: str = "world") -> str:
    """Say hello. Replace this with your first real tool."""
    return f"hello, {{who}}"


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
'''

    return f'''"""{name} — an MCP server with LEVH memory built in.

Generated by `levh mcp init --with-memory`. The memory tools come from the
installed LEVH package and read the same SQLite database as the dashboard and
every other LEVH client, so anything stored here shows up there too.

The "{profile}" tool profile is mounted. Change MEMORY_PROFILE below; run
`levh mcp profiles` to see what each one advertises.
"""

import sys
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from mcp.server.fastmcp import FastMCP

from server.core import engine_provider
from server.tools.register import register_all_tools

MEMORY_PROFILE = "{profile}"


@asynccontextmanager
async def _lifespan(_server: FastMCP) -> AsyncIterator[None]:
    """Open the database inside the server's own event loop.

    The connection must be created by the loop that will use it, so this
    cannot move into main() — an engine initialized in a separate
    asyncio.run() would be bound to a loop that is already closed.
    """
    engine = engine_provider.get_engine()
    await engine.initialize()
    try:
        yield
    finally:
        await engine.shutdown()


mcp = FastMCP("{name}", lifespan=_lifespan)


@mcp.tool()
def hello(who: str = "world") -> str:
    """Say hello. Replace this with your first real tool."""
    return f"hello, {{who}}"


# Registered at import time so the tools are advertised on initialize. The
# engine is created here; its connection is opened by the lifespan above and
# the embedder stays lazy until the first call.
_registered = register_all_tools(
    mcp, engine_provider.get_engine(), profile=MEMORY_PROFILE
)
# stdout is the stdio protocol channel — never print there.
print(
    f"[{name}] {{len(_registered)}} memory tools advertised "
    f"(profile: {{MEMORY_PROFILE}})",
    file=sys.stderr,
)


def main() -> None:
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
'''


def _readme(name: str, with_memory: bool, profile: str) -> str:
    memory_note = (
        f"""
## Memory

The LEVH memory tools are mounted with the `{profile}` profile. They read the
same SQLite database as the LEVH dashboard, so a memory stored through this
server is visible everywhere else — there is no separate store to sync.

Point it at a specific database with `SQLITE_DB_PATH`. Leave it unset to use
the LEVH default.

```bash
levh mcp profiles   # what each profile advertises
```
"""
        if with_memory
        else """
## Memory

This server was generated without memory tools. Re-run with `--with-memory`
to mount them, or add them yourself:

```python
from server.tools.register import register_all_tools
register_all_tools(mcp, engine, profile="work")
```
"""
    )

    return f"""# {name}

An MCP server generated by `levh mcp init`.

## Run it

```bash
pip install -r requirements.txt
cp .env.example .env      # then fill in what you need
python -m {module_name(name)}.server
```

The server speaks MCP over stdio, which is what Claude Desktop, Claude Code,
Cursor and the rest expect.

## Connect a client

Add this to your client's MCP config:

```json
{{
  "mcpServers": {{
    "{name}": {{
      "command": "python",
      "args": ["-m", "{module_name(name)}.server"]
    }}
  }}
}}
```
{memory_note}
## Add a tool

```python
@mcp.tool()
def my_tool(argument: str) -> str:
    \"\"\"One sentence saying what this does — the model reads this.\"\"\"
    return argument.upper()
```

Docstrings are not decoration here: they are how the model decides whether to
call your tool.
"""


def _env_example(with_memory: bool) -> str:
    lines = [
        "# Copy to .env and fill in what you need. Nothing here is required to",
        "# start the server — every value has a working default.",
        "",
    ]
    if with_memory:
        lines += [
            "# Where memories are stored. Unset uses the LEVH default, which is",
            "# what makes this server share a store with the dashboard.",
            "# SQLITE_DB_PATH=/absolute/path/to/levh.db",
            "",
            "# hash (default, offline, deterministic) | local | openai",
            "EMBEDDER_MODE=hash",
            "",
            "# Only needed when EMBEDDER_MODE=openai.",
            "# OPENAI_API_KEY=sk-...",
            "",
            "# Set when exposing the LEVH HTTP API beyond localhost.",
            "# LEVH_TOKEN=",
        ]
    else:
        lines += ["# Add your own settings here."]
    return "\n".join(lines) + "\n"


def _requirements(with_memory: bool) -> str:
    lines = ["mcp>=1.2.0"]
    if with_memory:
        lines.append("levh")
    return "\n".join(lines) + "\n"


def _gitignore() -> str:
    return "\n".join(
        [
            "__pycache__/",
            "*.py[cod]",
            ".env",
            "*.db",
            "*.db-wal",
            "*.db-journal",
            ".venv/",
        ]
    ) + "\n"


def generate_project(
    name: str,
    target_dir: str | Path,
    with_memory: bool = False,
    template: str = DEFAULT_TEMPLATE,
    profile: str = "work",
    force: bool = False,
) -> list[Path]:
    """Write a new MCP server project. Returns the files created."""
    project_name = normalize_name(name)
    if template not in TEMPLATES:
        raise ScaffoldError(
            f"unknown template '{template}'. Available: {', '.join(TEMPLATES)}"
        )

    root = Path(target_dir).expanduser().resolve() / project_name
    if root.exists() and any(root.iterdir()) and not force:
        raise ScaffoldError(
            f"'{root}' already exists and is not empty. Pass --force to write into it."
        )

    module = module_name(project_name)
    files: dict[str, str] = {
        f"{module}/__init__.py": "",
        f"{module}/server.py": _server_py(project_name, with_memory, profile),
        "README.md": _readme(project_name, with_memory, profile),
        ".env.example": _env_example(with_memory),
        "requirements.txt": _requirements(with_memory),
        ".gitignore": _gitignore(),
    }

    written: list[Path] = []
    for relative, content in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
