"""Context handed to the next session: context files and continuity.

Part of :class:`server.core.memory_engine.MemoryEngine`, split out to keep
each file readable. Mixins rather than separate services: the methods use the
engine's own state throughout, and moving the bodies unchanged is what makes
the split verifiable.
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..types import RULE_TAG
from ..types import (
    Memory,
)


class MemoryContinuityMixin:
    """Context handed to the next session: context files and continuity."""

    async def generate_context_file(
        self,
        project: str | None = None,
        style: str = "claude",
        max_memories: int = 60,
        max_rules: int = 10,
    ) -> str:
        """Compile memories into a persistent context file for AI clients.

        Args:
            project: Only include this project's memories (None = all).
            style: "claude" (CLAUDE.md) or "cursor" (.cursorrules).
            max_memories: Cap on included memories.
            max_rules: Cap on guard rules listed in their own section.
        """
        pinned = await self.episodic.search(project=project, pinned=True, limit=max_memories)
        important = await self.episodic.search(
            project=project, min_importance=0.7, limit=max_memories
        )
        recent = await self.episodic.search(project=project, limit=15)

        seen: set[str] = set()

        def _dedup(memories: list[Memory]) -> list[Memory]:
            out = []
            for m in memories:
                if m.id not in seen:
                    out.append(m)
                    seen.add(m.id)
            return out

        pinned = _dedup(pinned)
        important = [m for m in _dedup(important) if not m.pinned]
        recent = _dedup(recent)

        # Rules recorded by the mistake guard are pinned too, so split them out
        # of the generic pinned list rather than printing them twice. They lead
        # the file: a rule exists because ignoring it already cost something.
        rules = [m for m in pinned if RULE_TAG in (m.tags or [])]
        rules.sort(key=lambda m: (m.importance, m.created_at), reverse=True)
        pinned = [m for m in pinned if RULE_TAG not in (m.tags or [])]

        title = f"Project Memory — {project}" if project else "Project Memory"
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        lines: list[str] = []
        if style == "cursor":
            lines.append(f"# {title}")
            lines.append(f"# Generated by LEVH on {now}. Do not edit by hand.")
        else:
            lines.append(f"# {title}")
            lines.append("")
            lines.append(f"> Generated by LEVH on {now}. Do not edit by hand — ")
            lines.append("> update memories in LEVH and regenerate.")
        lines.append("")

        def _bullet(m: Memory) -> str:
            tags = f" _[{', '.join(m.tags)}]_" if m.tags else ""
            return f"- {m.content.strip()}{tags}"

        if rules:
            lines.append("## Rules Learned From Mistakes")
            lines.append("")
            lines.append("Each of these was recorded after the mistake it describes.")
            lines.append("")
            lines.extend(f"- {m.content.strip()}" for m in rules[:max_rules])
            lines.append("")
        if pinned:
            lines.append("## Always Remember (pinned)")
            lines.extend(_bullet(m) for m in pinned)
            lines.append("")
        if important:
            lines.append("## Key Decisions & Facts")
            lines.extend(_bullet(m) for m in important)
            lines.append("")
        if recent:
            lines.append("## Recent Context")
            lines.extend(_bullet(m) for m in recent[:10])
            lines.append("")

        if not (rules or pinned or important or recent):
            lines.append("_No memories stored yet._")

        return "\n".join(lines).rstrip() + "\n"

    async def get_continuity_context(
        self,
        task: str | None = None,
        project: str | None = None,
        limit: int = 5,
        since: str | None = None,
    ) -> str:
        """Synthesize a continuity brief from recent sessions and memories.

        Returns a human-readable brief showing where the user left off,
        including recent sessions, active files, decisions, and blockers.
        """
        from datetime import datetime, timezone

        # Get recent memories for context
        recent_memories = await self.episodic.search(
            project=project,
            limit=50,
        )

        # Get recent sessions for the project. Session metadata rarely carries
        # a "project" key, so a session also counts as belonging to the project
        # when any of the project's memories were recorded under it.
        sessions = await self.list_sessions(limit=limit * 2)
        if project:
            project_session_ids = {m.session_id for m in recent_memories if m.session_id}
            sessions = [
                s
                for s in sessions
                if s.metadata.get("project") == project or s.id in project_session_ids
            ]

        # Filter by date if since provided — before truncating to `limit`,
        # otherwise the cut-off list is filtered instead of the full one.
        if since:
            def _as_utc(value: str) -> datetime:
                # A bare date like "2026-01-01" parses as naive and cannot be
                # compared against the tz-aware timestamps we store, so assume UTC.
                parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
                return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)

            try:
                since_dt = _as_utc(since)
                sessions = [s for s in sessions if s.created_at and
                            _as_utc(s.created_at) >= since_dt]
            except ValueError:
                pass  # Invalid date format, ignore filter

        sessions = sessions[:limit]

        # Filter memories by session if we have sessions
        session_ids = {s.id for s in sessions}
        session_memories = [m for m in recent_memories if m.session_id in session_ids]

        # Also get git-hook memories (commits) for the project
        commit_memories = [m for m in recent_memories if m.source == "git-hook"]
        if project:
            commit_memories = [m for m in commit_memories if m.project == project]

        # Build the brief. `lines` holds only the header until a section adds
        # something, which is how the empty case is detected below — a brief
        # that is all frame and no content is noise, and this one is injected
        # into every new session.
        lines = []
        lines.append("=== LEVH Continuity Brief ===")
        lines.append("")
        header_only = len(lines)

        if task:
            lines.append(f"Task: {task}")
            lines.append("")

        # Rules and pinned memories come first, and they come from the pin flag
        # rather than from keyword guessing. Everything below this point is a
        # heuristic read of recent activity; this part is what the user
        # explicitly said never to forget, so it is the one section that must
        # not depend on a phrase matching a keyword list.
        pinned = [m for m in recent_memories if m.pinned]
        rules = [m for m in pinned if RULE_TAG in (m.tags or [])]
        notes = [m for m in pinned if RULE_TAG not in (m.tags or [])]

        if rules:
            lines.append("Rules (learned from mistakes — do not repeat these):")
            for r in sorted(rules, key=lambda m: m.importance, reverse=True)[:10]:
                lines.append(f"  ! {r.content.strip()}")
            lines.append("")

        if notes:
            lines.append("Always Remember (pinned):")
            for n in notes[:10]:
                snippet = n.content.strip().replace("\n", " ")[:160]
                lines.append(f"  - {snippet}")
            lines.append("")

        if sessions:
            lines.append(f"Recent Sessions ({len(sessions)}):")
            for s in sessions:
                status = "*" if s.status == "active" else "o"
                mem_count = s.memory_count
                project_info = s.metadata.get("project", "")
                proj_str = f" [{project_info}]" if project_info else ""
                lines.append(f"  {status} {s.name}{proj_str} - {mem_count} memories - {s.id[:8]}")
                if s.metadata.get("task"):
                    lines.append(f"      Task: {s.metadata['task']}")
            lines.append("")

        # Active files from commit memories
        if commit_memories:
            lines.append("Recent Changes (from commits):")
            seen_files = set()
            for m in commit_memories[:10]:
                # Extract file paths from commit messages
                import re
                files = re.findall(r'(\w+/\w+\.\w+|\w+\.\w+)', m.content)
                for f in files:
                    if f not in seen_files and len(seen_files) < 15:
                        seen_files.add(f)
                        lines.append(f"  - {f}")
            lines.append("")

        # Decisions from recent memories
        decisions = []
        for m in recent_memories[:30]:
            content_lower = m.content.lower()
            if any(kw in content_lower for kw in ["decided", "agreed", "karar", "seçtik", "we'll", "will use", "switching to"]):
                decisions.append(m)
        if decisions:
            lines.append("Recent Decisions:")
            for d in decisions[:5]:
                snippet = d.content[:120].replace("\n", " ")
                lines.append(f"  - {snippet}...")
            lines.append("")

        # Blockers / errors / TODOs
        blockers = []
        for m in recent_memories[:30]:
            content_lower = m.content.lower()
            if any(kw in content_lower for kw in ["error", "failed", "blocked", "todo", "fixme", "hata", "başarısız", "takıldı"]):
                blockers.append(m)
        if blockers:
            lines.append("Blockers / Errors / TODOs:")
            for b in blockers[:5]:
                snippet = b.content[:120].replace("\n", " ")
                lines.append(f"  ! {snippet}...")
            lines.append("")

        # Next suggested actions based on task
        if task:
            lines.append("Suggested Next Actions:")
            # Simple heuristic: if task mentions a file, suggest working on it
            if "test" in task.lower():
                lines.append("  1. Run failing tests")
                lines.append("  2. Fix test failures")
            elif "refactor" in task.lower():
                lines.append("  1. Continue refactoring")
                lines.append("  2. Run tests to verify")
            elif "bug" in task.lower() or "fix" in task.lower():
                lines.append("  1. Reproduce the bug")
                lines.append("  2. Implement fix")
            else:
                lines.append("  1. Continue from last session")
                lines.append("  2. Check recent decisions above")
            lines.append("")

        if len(lines) == header_only:
            return ""

        lines.append("=============================")
        return "\n".join(lines)
